site_name: MkDocs Template
site_url: https://example.com/
docs_dir: 'src'
# nav:
#     - Page 1: index.md
#     - Page 2: index.md
#     - Page 3: index.md
#     - Page 4: index.md
#     - About: about.md

theme:
#   name: mkdocs
  name: readthedocs
#   name: bootstrap
